# Use an official Node.js image
FROM node:22

# Set the working directory inside the container
WORKDIR /frontend

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies, leveraging Docker cache
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the default port for Vite
EXPOSE 5173

# Command to run the development server
CMD ["npm", "run", "dev"]
