name: Playwright E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Copy environment file
        run: cp backend/.env.example backend/.env

      - name: Build and start containers
        run: |
          docker compose build
          docker compose up -d

      - name: Run database migrations
        run: docker compose exec backend bin/rails db:migrate RAILS_ENV=development

      - name: Wait for backend to be ready
        run: |
          timeout=60
          elapsed=0
          echo "Waiting for backend API to be ready..."
          until docker compose exec frontend curl --output /dev/null --silent --fail http://backend:3000/ || [ $elapsed -gt $timeout ]; do
            sleep 5
            elapsed=$((elapsed+5))
            echo "Waiting for backend... ($elapsed seconds so far)"
          done

          if [ $elapsed -gt $timeout ]; then
            echo "Backend did not become ready in time"
            docker compose logs backend
            exit 1
          fi

      - name: Run Playwright E2E tests
        run: docker compose exec frontend npm run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

      - name: Cleanup
        if: always()
        run: docker compose down -v
