name: RSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose build
          docker compose up -d db

      - name: Run RSpec tests
        run: |
          docker compose run --rm backend sh -c "
            cp .env.example .env &&
            bundle exec rails db:create db:schema:load RAILS_ENV=test &&
            bundle exec rspec
          "
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:password@db:5432/ugood_test

      - name: Cleanup
        if: always()
        run: docker compose down -v
